# Site settings
title: "Logan Rath"
email: lrath@brockport.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://librarian.help" # the base hostname & protocol for your site

twitter_username: loganrath
github_username: loganrath

# Build settings
markdown: kramdown
