
title: My Resume
url: 'http://librarian.help'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3 #darkgreen
#style: styles-4 #purple
#style: styles-5 #orange
style: styles-6 #darkblue


#Profile information
name: Logan Rath
tagline: Associate Librarian
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: lrath@brockport.edu
phone: 585-395-2568
website: librarian.help  #do not add http://
linkedin: loganrath
github: loganrath
twitter: '@loganrath'

#Update all the sections by editing the files inside _includes folder.
